#168781675 - Signup/Register feature
andela/caret-bn-backend pull request #18
Opened 2019-10-08 13:39 UTC by nignanthomas

#### What does this PR do?
Create Signup/Register Feature

#### Description of Task to be completed?
- Create integration tests to test the signup endpoint
- Edit the models to add password and isVerified fields
- Create validators for signup request body
- Create helpers/utils for hashPassord, generate JWT token, verifyEmail and verifyUsername
- Create signupController and export to routes
- Create midllewares for checkSignup for the req.body, verifyEmail, verifyUsername, confirmPassword
- Create routes for 'api/v1/register/' with the aforementioned middlewares and signupController
- Change node version in Dockerfile from node:11-alpine to node:11 due to bcrypt crash

#### How should this be manually tested?
- Setup the Application first (refer to README.md)
- Run `npm run dev`
- Download Postman.
- In Postman, create a new POST request tab and enter the following URL: `http://localhost:3000/api/v1/users/register`.
- Enter the following user object as raw/json under `Body` Section: 
```
{
	"email": "johndoe@gmail.com",
	"username": "johndoe08",
	"password": "Pa55w0rd",
	"confirmPassword": "Pa55w0rd"
}
```
- You shoud have s similar response to the following:  
```
{
    "message": "User Created Successfully",
    "data": {
        "user_id": 1,
        "username": "johndoe08",
        "email": "johndoe@gmail.com",
        "created_at": "Tue Oct 08 2019 14:45:14 GMT+0200 (Central Africa Time)",
        "updated_at": "Tue Oct 08 2019 14:45:14 GMT+0200 (Central Africa Time)",
        "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7ImlkIjozfSwiaWF0IjoxNTcwNTM4NzE0LCJleHAiOjE1NzA2MjUxMTR9.2Xvj-XNmqouAhdSwUQviHz_QcrC7gxaWAU2vNZ9G_ps"
    }
}
```

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
[#168781675](https://www.pivotaltracker.com/story/show/168781675)

#### Screenshots (if appropriate)
<img width="1112" alt="Screen Shot 2019-10-08 at 15 26 52" src="https://user-images.githubusercontent.com/42959540/66399831-9435a300-e9e0-11e9-862b-47d0d20f34d6.png">

#### Questions:
N/A

2019-10-08 14:39 UTC, Cheza-Dzabala requested changes
Review the codeclimate warning please

2019-10-08 14:42 UTC, nignanthomas commented
> Review the codeclimate warning please

@Cheza-Dzabala Will do. Thanks
In the meantime, also check out the rest.

2019-10-09 15:57 UTC, alainmateso requested changes
Great Job Thomas. However, when returning validation errors to the user, please make sure all validation errors are returned at once instead of returning one by one(In the screenshot you can see that it only returns an error for the password, yet confirm password is also wrong).  I also hope you don't mind making them user-friendly and more descriptive. I think the first part of the message would be enough. Regards
<img width="1170" alt="Screen Shot 2019-10-09 at 17 53 58" src="https://user-images.githubusercontent.com/50104386/66498092-cd901080-eabd-11e9-8cb0-ddff6e82a2ec.png">

2019-10-09 20:07 UTC, zellymiriam commented on src/controllers/signupController.js
> +
Remove this line

2019-10-09 20:08 UTC, zellymiriam commented on src/controllers/signupController.js
> +  static async signupController({ body: { username, email, password } }, res) {
why are you using `async` and `static`

2019-10-09 20:10 UTC, zellymiriam commented on src/middlewares/checkSignup.js
> +export default function checkSignup({ body }, res, next) {
since we agreed to use es6 use arrow function

2019-10-09 20:11 UTC, zellymiriam commented on src/middlewares/confirmPassword.js
> +export default function confirmPassword({ body: { password, confirmPassword } }, res, next) {
since we agreed to use es6 use arrow function

2019-10-09 20:12 UTC, zellymiriam commented on src/middlewares/verifyExist.js
> +export default function verifyUserExist({ body: { username, email } }, res, next) {
since we agreed to use es6 use arrow function

2019-10-09 20:13 UTC, zellymiriam commented on src/utils/verifyUserExist.js
> +export default function verifyUserExist(res, property, message) {
since we agreed to use es6 use arrow function

2019-10-09 20:13 UTC, zellymiriam commented on src/validation/validateSignup.js
> +export default function validateSignup(data) {
since we agreed to use es6 use arrow function

2019-10-09 20:25 UTC, nakiwuge requested changes
@nignanthomas good job on the implementation. I have tested the feature and there is some feedback I would like you to work on.
- For security purposes, the password should contain at least 1  special character` #,@,?`
- The error returned to the user when the password is non-alphanumeric should be descriptive enough for the user...something like `Password should contain at least 1 letter,1 number and a special character`
- When the password or confirm password field is missing  a user should get an error `password required` or `confirmPasword required`
- The status code returned when a user successfully registers should be 201(created) not 200

I have also left comments on this pr

2019-10-10 09:39 UTC, Cheza-Dzabala approved these changes

2019-10-10 09:57 UTC, alainmateso approved these changes
Great Job @nignanthomas

2019-10-10 10:00 UTC, sabin18 approved these changes
It looks Good.

2019-10-10 10:03 UTC, ngireric123 approved these changes

2019-10-10 10:55 UTC, nakiwuge approved these changes

2019-10-10 10:55 UTC, merged