Ft signup email 168781676
andela/caret-bn-backend pull request #20
Opened 2019-10-10 16:21 UTC by ngireric123

#### What does this PR do?

- add user verify email

#### Description of Task to be completed?

- created email verification api

#### How should this be manually tested?

- Clone the repository from [here](https://github.com/andela/caret-bn-backend)
- got to to Ft-signup-email-168781676 branch
- Add SECRET_KEY variable to .env file
- Add SENDGRID_API_KEY=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
- Run npm install
- run sequelize db:migrate
- run sequelize db:seed:all
- run npm run dev

- in POSTMAN got http://localhost:3000/api/v1/users/register
- go to your e-mail and click verify email button

#### Any background context you want to provide?

- N/A

#### What are the relevant pivotal tracker stories?

[#168781676](https://www.pivotaltracker.com/story/show/168781676)

#### Screenshots (if appropriate)
<img width="1097" alt="Screen Shot 2019-10-10 at 18 17 27" src="https://user-images.githubusercontent.com/38130305/66587241-54aaba80-eb8a-11e9-8685-4b7ae79cfd15.png">

<img width="696" alt="Screen Shot 2019-10-10 at 18 19 13" src="https://user-images.githubusercontent.com/38130305/66587382-95a2cf00-eb8a-11e9-95b3-3666ff550e42.png">

<img width="796" alt="Screen Shot 2019-10-10 at 18 20 38" src="https://user-images.githubusercontent.com/38130305/66587443-b3703400-eb8a-11e9-9262-48f906bfd2ff.png">

#### Questions:
- N/A

2019-10-10 18:55 UTC, Cheza-Dzabala approved these changes

2019-10-10 20:21 UTC, nignanthomas requested changes
Great job @ngireric123 
Though you need to add the env variables to **.env.example**
And I didn't see tests, do you have tests?

2019-10-11 04:10 UTC, nignanthomas requested changes

2019-10-11 04:10 UTC, nignanthomas commented on src/controllers/userController.js
> +const { APP_URL_BACKEND } = process.env;
You should also make sure **APP_URL_BACKEND** is then heroku hostname when deployed.
And define all new env variables in **.env.example**

2019-10-11 09:52 UTC, alainmateso approved these changes

2019-10-11 09:54 UTC, sabin18 approved these changes
good job.

2019-10-11 09:55 UTC, nignanthomas approved these changes

2019-10-11 13:44 UTC, zellymiriam commented on src/controllers/userController.js
> +const APP_URL_BACKEND = process.env.NODE_ENV === 'development' ? `http://localhost:${process.env.APPLICATION_PORT}` : 'https://caret-bn-backend.herokuapp.com';
Make the `URL` dynamic you can pick the host and protocol from the request

2019-10-11 13:46 UTC, zellymiriam commented on src/database/config.js
> +    // port: process.env.DATABASE_PORT,
remove commented code

2019-10-11 13:46 UTC, zellymiriam commented on src/database/config.js
> +    // port: process.env.DATABASE_PORT,
remove commented code

2019-10-11 13:46 UTC, zellymiriam commented on src/tests/signupTest.spec.js
> +
remove empty line

2019-10-11 13:52 UTC, nakiwuge requested changes
@ngireric123 good job however I would like you to work on the feedback below
- Remove the token from the response data that is returned to the user on signup because a user can use it to verify their email without checking their emails.
- In your pr description, you added the secret API key of sendgrid. This is very dangerous. Only share such keys on the slack channel. Please remove it

I have added some other comments on the pr.

2019-10-13 14:45 UTC, nakiwuge approved these changes

2019-10-13 14:46 UTC, merged