#168781681 -User can reset password
andela/caret-bn-backend pull request #21
Opened 2019-10-10 19:33 UTC by sabin18

#### What does this PR do?
- user can Reset Password via email.

#### Description of Task to be completed?
- add send email verification function using SendGrid
- add reset password function 

#### How should this be manually tested?
- clone the repository : git clone https://github.com/andela/caret-bn-backend.git
- checkout to branch ft-reset-password-168781681
- do npm i
- add SENDGRID_API_KEY in your .env
- Go to/api/v1/forgotpassword to send Email  for link to reset password
- after go to the link you got in your email :`` /api/v1/resetpassword`` to reset password

#### Any background context you want to provide?
`N/A`

#### What are the relevant pivotal tracker stories?
[#168781681 ](https://www.pivotaltracker.com/n/projects/2400651)

#### Screenshots (if appropriate)
<img width="573" alt="Screen Shot 2019-10-10 at 21 26 53" src="https://user-images.githubusercontent.com/47029978/66600044-ede6ca80-eba4-11e9-9663-6581675d4597.png">
<img width="954" alt="Screen Shot 2019-10-10 at 21 28 05" src="https://user-images.githubusercontent.com/47029978/66600045-ee7f6100-eba4-11e9-8cd3-e406dadd7366.png">

#### Questions:
`N/A`

2019-10-11 14:20 UTC, alainmateso requested changes
Good job sending a reset email but when I click on the reset password button, it returns this message:

"status": 404,
"message": "Sorry this route does not exist !"
therefore I cannot fully test the feature . Kindly consider making sure that the functionality fully works!

2019-10-11 15:40 UTC, nignanthomas requested changes
Hey @sabin18, great job so far, keep it coming
However, the implementation of the feature is not complete and not secured.

You need to send a token created with the **generateToken** utils to create a token based on the user found by email together with the email. Then the user copies the token and add a token field to the **/resetpassword** request body that you decode in the patch to make it match the user email and decoded user from the token.
Only then, you can change the password.

If that does not make sense reach out tome

2019-10-14 14:36 UTC, nignanthomas requested changes

2019-10-14 14:36 UTC, nignanthomas commented on src/routes/api/index.js
> +// router.use('/forgotpassword', usersRoutes);
Remove the commented lines

2019-10-14 14:36 UTC, nignanthomas commented on src/routes/api/users.js
> + * /forgotpassword:
swagger route should be **users/forgotpassword**

2019-10-14 14:36 UTC, nignanthomas commented on src/routes/api/users.js
> + * /resetpassword:
swagger route should be **users/resetpassword/{token}** and have a parameter **"in:path"** for users to be able to pass in the **token**
Look at Eric's swagger doc for the verify token

2019-10-14 14:36 UTC, nignanthomas commented on src/controllers/userController.js
> +        <p><a style="background-color: #3097d1; border: 2px solid #3097d1; padding: 8px; color: #fff; font-size: 16px; text-decoration: none;cursor: pointer;" href="${req.protocol}://${req.headers.ho
I am still not convinced by you sending a link that tells me **404, route not found**. As a user what do I do when I get this? I think it is broken. Reach out to @zellymiriam  as soon as possible @sabin18, if she agrees with that implementation, but I am not convinced

2019-10-14 15:15 UTC, alainmateso approved these changes

2019-10-14 15:37 UTC, nignanthomas approved these changes

2019-10-14 19:05 UTC, ngireric123 approved these changes

2019-10-15 11:26 UTC, zellymiriam commented on src/utils/EmailToken.js
> +  const decodedToken = jwt.decode(token, process.env.JWT_SECRET);
Add a new line

2019-10-15 11:27 UTC, zellymiriam commented on src/utils/EmailToken.js
> +
Remove this line

2019-10-15 11:27 UTC, zellymiriam commented on src/validation/validateResetpassword.js
> +};
Add a new line

2019-10-15 11:29 UTC, zellymiriam commented on src/utils/EmailToken.js
> +const ResetToken = user => {
I believe there is already a function for generating a token. Why don`t you use the same function?

2019-10-15 11:31 UTC, nakiwuge requested changes
@sabin18 good job. I realized you left out the `confirmPassword` field. Please add it. Also I have left some comments you should check out.

2019-10-16 08:39 UTC, nakiwuge approved these changes

2019-10-16 08:40 UTC, merged