#168781683 user profile setting
andela/caret-bn-backend pull request #26
Opened 2019-10-16 17:05 UTC by ngireric123

[finishes #168781683]

#### What does this PR do?
allow user to edit his/her profile settings
#### Description of Task to be completed?
- add endpoint for update user settings
#### How should this be manually tested?
- Clone the repository from [here](https://github.com/andela/caret-bn-backend.git)
- Go to the repo directory
- Go to Ft-profile-setting-168781683 branch
- Run `npm install`
- Go to the following url https://developers.google.com/oauthplayground/ and authorize the following APIs (This is done in step 1 of the Playground process).
 a) Google OAuth apiv2
      - https://www.googleapis.com/auth/userinfo.email
      - https://www.googleapis.com/auth/userinfo.profile
- Exchange the authorization code for tokens (This is done in step 2 of the Playground process)
- Copy the new access token for your `GOOGLE_ACCESS_TOKEN=` in your .env file

- run `sequelize db:migrate`
- run `sequelize db:seed:all`
- run `npm run dev`
 **Edit profile**
- In Postman Provide a login bearer token
- Fill the body with all data you want to edit
- send a `PATCH` request to `http://localhost:<patch>/api/v1/users/{email}`

#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
https://www.pivotaltracker.com/story/show/168781683
#### Screenshots (if appropriate)
![image](https://user-images.githubusercontent.com/38130305/66941674-b5813980-f047-11e9-858e-760a678299c5.png)
![image](https://user-images.githubusercontent.com/38130305/66941744-dea1ca00-f047-11e9-890c-433614ea5748.png)

#### Questions:
N/A

2019-10-18 08:31 UTC, alainmateso commented on src/database/migrations/20190930143254-User.js
> +    // },
Please remove commented code!

2019-10-18 08:42 UTC, nignanthomas requested changes
Great job @ngireric123. I tried it and it seems to work fine.
However, I would like you to add a few more tests, like
- when the ***token is malformed**
- when there is **no token**
- when the **payload email !== req.params.email**
Those lines seem to not be covered by tests.

2019-10-18 08:42 UTC, alainmateso commented on src/controllers/profile.js
> +}
Please respect naming conventions when naming files. I think this file should be profileController.js

2019-10-18 08:46 UTC, alainmateso requested changes
You have done a good job Eric! However, there are some changes I would like you to implement like naming conventions, removing commented code, removing duplicated files or having multiple files that do the same thing(Files that sign the token, files that decode the token...). Kindly look into that!

2019-10-18 18:46 UTC, alainmateso approved these changes
Awesome

2019-10-21 09:27 UTC, sabin18 approved these changes
good job @ngireric123

2019-10-21 09:41 UTC, nignanthomas approved these changes

2019-10-22 07:41 UTC, zellymiriam commented on src/controllers/profileController.js
> +      } = newUser[1].dataValues;
Add a newline here

2019-10-22 07:41 UTC, zellymiriam commented on src/controllers/profileController.js
> +      });
Add a new line here

2019-10-22 07:41 UTC, zellymiriam commented on src/controllers/profileController.js
> +      }
Add a newline here

2019-10-22 07:43 UTC, zellymiriam commented on src/routes/api/users.js
> +router.patch('/:email', validateToken, validateProfile, updateProfile);
this route should also be `/profile/:email`

2019-10-22 07:45 UTC, nakiwuge requested changes
@ngireric123 good job with the implementation. I have left a few comments kindly check them out.

2019-10-22 12:57 UTC, nakiwuge approved these changes

2019-10-22 12:57 UTC, merged