#169113466 - Edit and Delete Accommodation Facilities
andela/caret-bn-backend pull request #27
Opened 2019-10-17 04:23 UTC by nignanthomas

#### What does this PR do?
Edit and Delete Accommodation Facilities

#### Description of Task to be completed?
- Create tests cases for edit an accommodation and delete an accommodation features
- Create verifyToken, checkId, isAccommodationFound, isOwner middlewares to validate informations
- Create editAccommodation and deleteAccommodation controllers

#### How should this be manually tested?
- Clone the repository from [here](https://github.com/andela/caret-bn-backend.git)
- Browse to the repo directory
- navigate to ft-create-accommodation-168781707 branch
- Run `npm install`
- Refer to .env.example and add `CLOUDINARY_URL=`
- Go to the following url https://developers.google.com/oauthplayground/ and authorize the following APIs (This is done in step 1 of the Playground process).
 a) Google OAuth apiv2
      - https://www.googleapis.com/auth/userinfo.email
      - https://www.googleapis.com/auth/userinfo.profile
- Exchange the authorization code for tokens (This is done in step 2 of the Playground process)
- Copy the new access token for your `GOOGLE_ACCESS_TOKEN=` in your .env file

- run `sequelize db:migrate`
- run `sequelize db:seed:all`
- run `npm run dev`
 **To edit an accommodation**
- In Postman Provide a login bearer token
- Fill the body with all fields you want to amend
- send a `PATCH` request to `http://localhost:<port>/api/v1/accommodations/{id}/edit`
**To delete an accommodation**
- In Postman Provide a login bearer token
- send a `DELETE` request to `http://localhost:<port>/api/v1/accommodations/{id}/delete`

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
[#169113466](https://www.pivotaltracker.com/story/show/169113466)

#### Screenshots (if appropriate)

#### Questions:
N/A

2019-10-17 14:22 UTC, Cheza-Dzabala requested changes
Update the location field to locationId and we're golden.

2019-10-17 16:25 UTC, alainmateso approved these changes
God Job Thomas!

2019-10-17 16:31 UTC, ngireric123 approved these changes

2019-10-17 17:17 UTC, nignanthomas commented
> Update the location field to locationId and we're golden.

Changes implemented + Refactoring 👍

2019-10-18 05:27 UTC, Cheza-Dzabala approved these changes

2019-10-18 09:19 UTC, zellymiriam commented on src/controllers/accommodationController.js
> +    const { body } = req;
Add a new line here

2019-10-18 09:20 UTC, nakiwuge commented on src/controllers/accommodationController.js
> +    const { accommodation } = req;
Add a new line here

2019-10-18 09:20 UTC, zellymiriam commented on src/controllers/accommodationController.js
> +    }
Add a new line here

2019-10-18 09:48 UTC, nakiwuge commented on src/middlewares/isAccommodationFound.js
> +  const accommodationId = parseInt(id, 10);
Add a new line here

2019-10-18 09:55 UTC, zellymiriam commented on src/utils/validationChecker.js
> +
I do not understand why we have so many validation methods in every feature

2019-10-20 10:05 UTC, merged