#168781689- admin can assign role to user
andela/caret-bn-backend pull request #28
Opened 2019-10-17 20:46 UTC by sabin18

#### What does this PR do?
PR to add role settings and admin controller.
#### Description of Task to be completed?
- created get all user function. 
- created  get one user function.
- created   get roles function.
- created  assign roles function.
- created  roles seeders.
- created  admin permission.
#### How should this be manually tested?
- clone the repository : git clone https://github.com/andela/caret-bn-backend.git
- checkout to branch ft-User-Role-Settings-168781689
- run sequelize db:migrate
- run sequelize db:seed:all
- Login as admin
- Take the token to your headers in authorization as Bearer Token to each routes of this feature.
- Get all users : /api/v1/admin/users/
- Get all roles : /api/v1/admin/users/roles/
- Get one user or single user : /api/v1/admin/users/:id   :id=>user id
- Assign role to user: /api/v1/admin/assign/:id                 :id=>user id
- to add role to user you write the name of role you want to give to the user in the body as Role.

#### Any background context you want to provide?
`N/A`
#### What are the relevant pivotal tracker stories?
[168781689](https://www.pivotaltracker.com/story/show/168781689)
#### Screenshots (if appropriate)
<img width="1134" alt="Screen Shot 2019-10-17 at 22 35 28" src="https://user-images.githubusercontent.com/47029978/67045725-28b1ab00-f12f-11e9-91b4-461206c32ce7.png">
<img width="1134" alt="Screen Shot 2019-10-17 at 22 37 28" src="https://user-images.githubusercontent.com/47029978/67045727-28b1ab00-f12f-11e9-9d1e-559f21e35bb8.png">
<img width="1134" alt="Screen Shot 2019-10-17 at 22 38 31" src="https://user-images.githubusercontent.com/47029978/67045728-28b1ab00-f12f-11e9-9a70-a0c7706fc4c3.png">
<img width="1134" alt="Screen Shot 2019-10-17 at 22 39 11" src="https://user-images.githubusercontent.com/47029978/67045729-294a4180-f12f-11e9-9da2-83b98238bbb2.png">

#### Questions:
`N/A`

2019-10-18 10:00 UTC, alainmateso requested changes
Good Job Sabin! I would like for you to impolement some changes though. Like re-using the existing token validation that handles even incorrect tokens(which yours doen't) instead of creating a new one as well as implementing your input validations into the existing validation class.

2019-10-18 16:06 UTC, alainmateso approved these changes
Great job Sabin

2019-10-18 16:06 UTC, nignanthomas requested changes
Woow, great job @sabin18 !
However
- remove the **password** in the returned users and you shall be good.
Even a Super Admin can't see users' passwords.
- the endpoints break when **id !== integer** eg: /admin/users/wa
I have a checkId middleware that you will be able to reuse when my feature is merged

2019-10-20 13:18 UTC, nignanthomas approved these changes

2019-10-22 08:34 UTC, zellymiriam commented on src/controllers/adminController.js
> +
Remove this line

2019-10-22 08:35 UTC, zellymiriam commented on src/controllers/adminController.js
> +      if (user == null) {
You can write if `!user` instead if `user == null`

2019-10-22 08:36 UTC, zellymiriam commented on src/controllers/adminController.js
> +
Remove this line

2019-10-22 08:36 UTC, zellymiriam commented on src/controllers/adminController.js
> +
Remove this line

2019-10-22 08:40 UTC, zellymiriam commented on src/database/migrations/20191007121953-addPasswordAndVerificationColumns.js
> +      type: Sequelize.INTEGER,
This should be a foreign key

2019-10-22 08:41 UTC, zellymiriam commented on src/middlewares/permissions.js
> +
Remove this line

2019-10-22 08:41 UTC, zellymiriam commented on src/middlewares/permissions.js
> +
Remove this line

2019-10-22 08:42 UTC, zellymiriam commented on src/routes/api/admin.js
> +
Remove this line

2019-10-22 08:42 UTC, zellymiriam commented on src/routes/api/admin.js
> +
Remove this line

2019-10-22 08:43 UTC, zellymiriam commented on src/routes/api/admin.js
> +router.patch('/assign/:id', validateToken, AdminAccess, checkId, validateRole, AssignRoles);
change this route to `roles/assign/:id`

2019-10-22 08:43 UTC, zellymiriam commented on src/tests/mockdata.js
> +
Remove this line

2019-10-22 08:43 UTC, zellymiriam commented on src/tests/mockdata.js
> +
Remove this line

2019-10-22 08:47 UTC, nakiwuge requested changes
Good work @sabin18. Kindly work on the feedback below.
- Add an association between the roles and users table
- Return the roles object as the value to the key `role` when getting a user
I have left other comments on the pr.

2019-10-22 15:23 UTC, nakiwuge approved these changes

2019-10-22 15:23 UTC, merged