#168781691 approve/reject request
andela/caret-bn-backend pull request #30
Opened 2019-10-23 09:10 UTC by alainmateso

#### What does this PR do?
Give a manager the ability to approve or reject a request

#### Description of Task to be completed?
- adds the possibility for a manager to view requests awaiting their decision
- adds the possibility for requesters to view all requests they have submitted
- adds the possibility for a manager to approve or reject requests

#### How should this be manually tested?
- Clone the repository from [here](https://github.com/andela/caret-bn-backend.git)
- Browse to the repo directory
- navigate to ft-approve-reject-request-168781691 branch
- Run `npm install`
- run `sequelize db:migrate`
- run `sequelize db:seed:all`
- run `npm run dev`

- To view requests

Log in
Send a GET request to http://localhost:<port>/api/v1/requests
* If you are logged in as a manager, you will have a list of requests that are awaiting your decision
* If you are logged in as a requester, you will have a list of requests that you have submitted

- To approve a request

Log in as a manager
Send a PATCH request to http://localhost:<port>/api/v1/requests/approve/<requestId>

- To reject a request

Log in as a manager
Send a PATCH request to http://localhost:<port>/api/v1/requests/reject/<requestId>

#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
[#168781691
](https://www.pivotaltracker.com/story/show/168781691)

#### Screenshots (if appropriate)
<img width="1168" alt="Screen Shot 2019-10-23 at 10 07 05" src="https://user-images.githubusercontent.com/50104386/67375774-6e350480-f583-11e9-8bf2-7f13183f3807.png">
<img width="1168" alt="Screen Shot 2019-10-23 at 10 44 07" src="https://user-images.githubusercontent.com/50104386/67375792-768d3f80-f583-11e9-8649-4e22ab82cec0.png">
<img width="1168" alt="Screen Shot 2019-10-23 at 10 55 29" src="https://user-images.githubusercontent.com/50104386/67375984-adfbec00-f583-11e9-8087-ffaa2c96c747.png">

#### Questions:
N/A

2019-10-23 15:38 UTC, sabin18 commented on src/database/models/requeststatus.js
> +  // requestStatus.associate = function (models) {
remove these comments

2019-10-23 16:11 UTC, sabin18 requested changes
good job @alainmateso ,please update your PR with correct routes, you forgot to add ID.When manager get response he still get that request is pending, it require to click twice.So work on that .

2019-10-24 07:51 UTC, Cheza-Dzabala approved these changes
Checked. I approve.

2019-10-24 08:51 UTC, sabin18 approved these changes
good job @alainmateso

2019-10-24 12:42 UTC, zellymiriam commented on src/controllers/requestController.js
> +
Remove this line

2019-10-24 12:48 UTC, zellymiriam commented on src/routes/api/requests.js
> +router.patch('/approve/:id', validateToken, checkManagerRole, checkId, approveRequest);
Change this to `manager/approve/:id`

2019-10-24 12:49 UTC, zellymiriam commented on src/routes/api/requests.js
> +router.patch('/reject/:id', validateToken, checkManagerRole, checkId, rejectRequest);
Change this to `manager/reject/:id`

2019-10-24 12:53 UTC, zellymiriam commented on src/controllers/requestController.js
> +    });
Create a helper function for this query

2019-10-24 12:58 UTC, nakiwuge requested changes
great job @alainmateso,  I have left comments kindly check them out.

2019-10-26 16:44 UTC, nakiwuge approved these changes

2019-10-26 16:44 UTC, merged