Ft user make request 168781684
andela/caret-bn-backend pull request #31
Opened 2019-10-23 18:56 UTC by Cheza-Dzabala

#### What does this PR do?

#### Description of Task to be completed?

#### How should this be manually tested?

#### Any background context you want to provide?

#### What are the relevant pivotal tracker stories?

#### Screenshots (if appropriate)

#### Questions:

2019-10-24 09:25 UTC, alainmateso requested changes
Great Job so far @Cheza-Dzabala . However, Please return data objects in your response where possible like the location's name at least. Make sure the problems of the departure date at the destination that can be greater than the return date are also fixed.

2019-10-24 10:11 UTC, nignanthomas requested changes
Impressive job with your validations @Cheza-Dzabala 👏 
Just implement the changes I told you on Slack

* tables foreignKeys should be >=1

* suppliers wich are external to the company should not be able to place requests.

2019-10-24 10:37 UTC, zellymiriam commented on src/controllers/destinationController.js
> +
Remove this line

2019-10-24 10:37 UTC, zellymiriam commented on src/controllers/requestController.js
> +
Remove this line

2019-10-24 10:38 UTC, zellymiriam commented on src/middlewares/requests/bookingsVerification.js
> +
Remove this line

2019-10-24 10:40 UTC, zellymiriam commented on src/middlewares/requests/bookingsVerification.js
> +const checkMultiple = destinations => {
What are you trying to achieve with this function?

2019-10-24 10:41 UTC, nakiwuge commented on src/middlewares/requests/datesVerification.js
> +  for (let counter = 0; counter < destinations.length; counter += 1) {
Why are you using a for loop here? What do you want to achieve?

2019-10-24 10:42 UTC, zellymiriam commented on src/middlewares/requests/datesVerification.js
> +  for (let counter = 0; counter < requests.length; counter += 1) {
Why are you using a for loop here? What do you want to achieve?

2019-10-24 10:43 UTC, zellymiriam commented on src/middlewares/requests/destinationVerification.js
> +  for (let counter = 0; counter < destinations.length; counter += 1) {
Why are you using a for loop here? What do you want to achieve?

2019-10-24 10:45 UTC, zellymiriam commented on src/middlewares/requests/locationVerification.js
> +
Remove this line

2019-10-24 10:46 UTC, zellymiriam commented on src/middlewares/requests/locationVerification.js
> +  for (let counter = 0; counter < destinations.length; counter += 1) {
Why are you using a for loop here?

2019-10-24 10:47 UTC, zellymiriam commented on src/middlewares/requests/locationVerification.js
> +  for (let counter = 0; counter < destinations.length; counter += 1) {
Why are you using a for loop here?

2019-10-24 10:48 UTC, zellymiriam commented on src/middlewares/requests/relationVerification.js
> +
Remove this line

2019-10-24 10:48 UTC, nakiwuge commented on src/middlewares/requests/relationVerification.js
> +
Remove this line

2019-10-24 10:48 UTC, zellymiriam commented on src/middlewares/requests/relationVerification.js
> +  for (let counter = 0; counter < destinations.length; counter += 1) {
Why are you using a for loop here?

2019-10-29 07:27 UTC, alainmateso approved these changes

2019-10-29 07:56 UTC, nignanthomas approved these changes

2019-10-29 11:33 UTC, merged