#168781708-user can book accommodation
andela/caret-bn-backend pull request #32
Opened 2019-10-24 00:26 UTC by sabin18

#### What does this PR do?
- It allow user to view all available accommodation and book an accommodation.
#### Description of Task to be completed?
- add view all available accommodation function
- add booking function
#### How should this be manually tested?
- clone the repository : git clone https://github.com/andela/caret-bn-backend.git
- checkout to branch ft-book-accommodation-168781708
- run sequelize db:migrate
- run sequelize db:seed:all
- Login 
- Take the token to your headers in authorization as Bearer Token to each routes of this feature
- use this route to view all available accommodations : /api/v1/accommodations/available
- use this route to book an accommodation :/api/v1/accommodations/booking/:id   id=>accommodation id
#### Any background context you want to provide?
`N/A`
#### What are the relevant pivotal tracker stories?
[168781708](https://www.pivotaltracker.com/story/show/168781708)
#### Screenshots (if appropriate)

#### Questions:
`N/A`

2019-10-24 12:17 UTC, ngireric123 approved these changes

2019-10-24 12:23 UTC, ngireric123 commented on src/controllers/accommodationController.js
> +  static BookAccommdation(req, res) {
follow naming convention we use

2019-10-24 15:34 UTC, alainmateso requested changes
Good job @sabin18 . However, please ensure that you make the necessary validations. For example, I can book an accommodation with dates that have already passed. Please look into that. Also, the error messages returned on the wrong date formats should be a date format not a date itself.

2019-10-25 06:56 UTC, alainmateso approved these changes

2019-10-25 13:48 UTC, zellymiriam commented on src/controllers/accommodationController.js
> +      attributes: { exclude: ['locationId', 'owner'] },
Add the owner object to the response

2019-10-25 13:50 UTC, zellymiriam commented on src/controllers/accommodationController.js
> +    const { checkInDate, checkOutDate } = req.body;
Add `accomodationId` and `numberRooms` to the req.body

2019-10-25 13:54 UTC, zellymiriam commented on src/controllers/accommodationController.js
> +        }
Make this a helper function to be reused

2019-10-25 13:54 UTC, zellymiriam commented on src/controllers/accommodationController.js
> +        if (moment(checkOutDate) < moment.now() || moment(checkOutDate) < moment.now()) {
Make this a helper function to be reused

2019-10-25 13:59 UTC, zellymiriam commented on src/routes/api/accommodations.js
> +
remove this line

2019-10-25 14:00 UTC, zellymiriam commented on src/routes/api/accommodations.js
> +router.patch('/booking/:id', validateToken, checkId, validateDate, bookAccommdation);
Change this route to `/book` and remove the param

2019-10-25 14:06 UTC, nakiwuge requested changes
Good job @sabin18, I have left comments on this pr. Also kindly add a route `/bookings` that will allow users to view their bookings

2019-10-28 15:46 UTC, nakiwuge approved these changes

2019-10-28 16:34 UTC, merged