#168781697 - Add Search Functionality on Requests
andela/caret-bn-backend pull request #33
Opened 2019-10-24 08:25 UTC by nignanthomas

#### What does this PR do?
Add Search Functionality

#### Description of Task to be completed?
- Create tests
- Create searchServices
- Create validation for the search options
- Create controller

#### How should this be manually tested?
- Clone the repository from [here](https://github.com/andela/caret-bn-backend.git)
- Browse to the repo directory
- navigate to ft-approve-reject-request-168781691 branch
- Run `npm install`
- run `sequelize db:migrate`
- run `sequelize db:seed:all`
- run `npm run dev`

**- To Search Requests**
* If you are logged in as a manager
Send a POST request to `http://localhost:port/api/v1/requests/manager/search`
* If you are logged in as a requester
Send a POST request to `http://localhost:port/api/v1/requests/search`

With one or more of the following fields
```
{
    id: integer(a request id),
    userId: integer(a user id - /manager/search route only),
    origin: integer (a location id - kindly query the locations routes to have a list of locations)
    statusId: integer (a status id - 1 for Pending, 2 for, Rejected 3 for Approved )
    reasons: "string"(a keyword to search for in the reasons)
    startDate: "YYYY-MM-DD"
    destination: integer (a location id - kindly query the locations routes to have a list of locations)
}
```

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
[#168781697](https://www.pivotaltracker.com/story/show/168781697)

#### Screenshots (if appropriate)
<img width="1133" alt="Screen Shot 2019-10-24 at 09 50 39" src="https://user-images.githubusercontent.com/42959540/67467083-7440e900-f648-11e9-9224-6a9797456b70.png">
<img width="1121" alt="Screen Shot 2019-10-24 at 09 51 21" src="https://user-images.githubusercontent.com/42959540/67467091-773bd980-f648-11e9-8d3a-c4755a7e4e02.png">
<img width="1124" alt="Screen Shot 2019-10-24 at 10 22 16" src="https://user-images.githubusercontent.com/42959540/67467102-799e3380-f648-11e9-8ec1-a712d2910e72.png">
<img width="1125" alt="Screen Shot 2019-10-24 at 10 23 34" src="https://user-images.githubusercontent.com/42959540/67467120-7dca5100-f648-11e9-9617-8267da80dbd7.png">

#### Questions:
N/A

2019-10-25 09:31 UTC, sabin18 requested changes
good job @nignanthomas but i found some changes that you can work on validation messages should be specific, reason letters should be above 3 letters .DepartureDate  search is  not working and change the PR where the startDate should be departureDate.

2019-10-25 10:26 UTC, ngireric123 approved these changes
good job @nignanthomas

2019-10-25 14:24 UTC, zellymiriam commented on src/controllers/requestController.js
> +
Remove this line

2019-10-25 14:28 UTC, zellymiriam commented on src/middlewares/managerUserIdField.js
> +    const myUsers = [];
Add a new line

2019-10-25 14:29 UTC, zellymiriam commented on src/middlewares/managerUserIdField.js
> +  }
Add a new line

2019-10-25 14:29 UTC, zellymiriam commented on src/middlewares/managerUserIdField.js
> +  });
Add a new line

2019-10-25 14:29 UTC, zellymiriam commented on src/routes/api/requests.js
> +
remove this line

2019-10-25 14:31 UTC, zellymiriam commented on src/routes/api/requests.js
> +router.post('/manager/search', validateToken, supplierNotAllowed, checkManagerRole, validateSearchRequestManager, managerUserIdField, requestController.searchRequests);
This should be a `get` method. Use query params for search

2019-10-25 14:31 UTC, zellymiriam commented on src/tests/searchRequestsTests.spec.js
> +
remove this line

2019-10-25 14:32 UTC, zellymiriam commented on src/tests/searchRequestsTests.spec.js
> +
remove this line

2019-10-25 14:33 UTC, zellymiriam commented on src/utils/requestsSearch.js
> +      let { returnDate } = request.dataValues;
Add a new line

2019-10-25 14:35 UTC, nakiwuge requested changes
@nignanthomas great job sofar however kindly use query params for search. I have left other comments on the pr.

2019-10-26 19:54 UTC, sabin18 approved these changes
good job @nignanthomas.

2019-10-26 20:05 UTC, zellymiriam commented on src/database/models/destinations.js
> -    accomodationId: DataTypes.INTEGER,
Why have you removed the `accomodationId`?

2019-10-28 08:52 UTC, nakiwuge approved these changes

2019-10-28 11:03 UTC, merged