ft(edit trip request): user should be able to edit his/her trip request
andela/caret-bn-backend pull request #34
Opened 2019-10-25 08:23 UTC by ngireric123

[starts #168781705]

#### What does this PR do?

Update trip request 

#### Description of Task to be completed?

- added modify controller
- added request middleware
- added routes
#### How should this be manually tested?
- Clone the repository from [here](https://github.com/andela/caret-bn-backend.git)
- Browse to the repo directory
- navigate to Ft-update-request-168781705 branch
- Run `npm install`
- run `sequelize db:migrate`
- run `sequelize db:seed:all`
- run `npm run dev`

**- To Search Requests**
* If you are logged in 
Send a PATCH request to `http://localhost:port/api/v1/requests/:ID`

Postman body example
```
{
	"typeId": 3,
	"locationId": 1,
	
	"destinations": [
		{
			"id": 1,
			"reasons": "visit andela"
		},
		{
			"id":2,
		"reasons": "visit andela nigeria office"
		}
		]
}
```

#### Any background context you want to provide?

N/A

#### What are the relevant pivotal tracker stories?
[#168781705](https://www.pivotaltracker.com/story/show/168781705)

#### Screenshots (if appropriate)
![image](https://user-images.githubusercontent.com/38130305/67555352-673bfc80-f711-11e9-9ca3-c64269c38694.png)

![image](https://user-images.githubusercontent.com/38130305/67555414-89357f00-f711-11e9-9269-a60daab1a372.png)

#### Questions:

2019-10-29 11:12 UTC, alainmateso requested changes
Good Job @ngireric123 . Kindly make your error messages descriptive to tell the user what exactly they are doing it wrong. Also, make a validation for the params id because when I pass an incorrect id format the app breaks. 
<img width="1149" alt="Screen Shot 2019-10-29 at 13 04 04" src="https://user-images.githubusercontent.com/50104386/67762290-c8cfd400-fa4d-11e9-85a6-a0a080d68d5e.png">

2019-10-29 12:07 UTC, nignanthomas requested changes
Great job @ngireric123 so far. It was a long road.

However, I suggest you have more descriptive error messages.
eg: You are not the owner of this request-id, 
or for destinations' id => You are not the owner of this destination id.
In short, more descriptive messages.

Kindly make sure you test your feature extensively, why has the **test coverage** dropped by **2.5%**?

Thanks

2019-10-30 08:11 UTC, zellymiriam commented on src/middlewares/inputValidation.js
> +
Remove this line

2019-10-30 08:11 UTC, zellymiriam commented on src/middlewares/inputValidation.js
> +    let maximumItems = 30;
Add an empty line

2019-10-30 08:12 UTC, zellymiriam commented on src/middlewares/inputValidation.js
> +    }
Add an empty line

2019-10-30 08:13 UTC, zellymiriam commented on src/middlewares/inputValidation.js
> +    }
Add a new line

2019-10-30 08:26 UTC, zellymiriam commented on src/middlewares/request.js
> +    const requester = await requests.findOne({
Create a helper function for this query

2019-10-30 08:32 UTC, zellymiriam commented on src/middlewares/request.js
> +    const destination = req.body;
Are you using this cont anywhere? If not remove it.

2019-10-30 08:32 UTC, zellymiriam commented on src/middlewares/request.js
> +
Remove this line

2019-10-30 08:43 UTC, nakiwuge requested changes
@ngireric123 good job on the implementation however kindly work on the feedback below.
-  Test `validateRequest.js` function to increase coverage.
- Ensure that a user can edit a return date
- Go through the comments I have left on your pr

2019-10-30 14:45 UTC, alainmateso approved these changes

2019-10-30 14:52 UTC, nignanthomas approved these changes

2019-10-30 20:49 UTC, nakiwuge approved these changes

2019-10-30 20:49 UTC, merged