#168781696 -user can edit/delete comment
andela/caret-bn-backend pull request #38
Opened 2019-10-29 15:45 UTC by sabin18

#### What does this PR do?
PR to allow user to edit or delete his comment
#### Description of Task to be completed?
- add editComment function
- add deleteComment function
- add comment table
#### How should this be manually tested?
- clone the repository : git clone https://github.com/andela/caret-bn-backend.git
- checkout to branch ft-edit-comment-168781696
- run sequelize db:migrate
- run sequelize db:seed:all
- use this route to edit comment `PUT :/api/v1/requests/comments/:id` id=>comment id.
- add comment in your body when you are editing comment.
- use this route to delete comment `DELETE: /api/v1/requests/comments/:id` id=>comment id.
#### Any background context you want to provide?
`N/A`
#### What are the relevant pivotal tracker stories?
[168781696](https://www.pivotaltracker.com/story/show/168781696)
#### Screenshots (if appropriate)
<img width="1026" alt="Screen Shot 2019-10-31 at 14 52 28" src="https://user-images.githubusercontent.com/47029978/67949734-ed17e600-fbf0-11e9-9811-91813ae730f9.png">
<img width="1026" alt="Screen Shot 2019-10-31 at 15 16 30" src="https://user-images.githubusercontent.com/47029978/67950083-aecef680-fbf1-11e9-865c-6c89f005206f.png">

#### Questions:
`N/A`

2019-10-30 11:56 UTC, Cheza-Dzabala requested changes
Hello Roger,

This is what I've discovered. When I send an empty body of data I am returned with "Message Updated Successfully" please rectify this.

2019-10-30 12:54 UTC, nignanthomas commented on src/controllers/commentsController.js
> +  }
your methods to `edit` and to `delete` are very much similar.
Kindly refactor it.
**Suggestion:** 
- Create a helper to find a comment, by passing the required parameters in the helper
- A helper to check if **not found** and **not owner**
- Then one to update by passing the required parameters in the helper.

2019-10-30 12:55 UTC, nignanthomas commented on src/controllers/commentsController.js
> +    });
This the delete method I was talking about.
Kindly refactor.

2019-10-30 12:57 UTC, nignanthomas requested changes
Great job @sabin18 
Kindly implement the changes I requested and we are good

2019-10-30 15:16 UTC, nignanthomas approved these changes

2019-10-31 07:56 UTC, Cheza-Dzabala approved these changes

2019-10-31 08:56 UTC, zellymiriam commented on src/controllers/commentsController.js
> +
remove this line

2019-10-31 08:57 UTC, zellymiriam commented on src/controllers/commentsController.js
> +
remove this line

2019-10-31 08:57 UTC, zellymiriam commented on src/controllers/commentsController.js
> +
remove this line

2019-10-31 08:57 UTC, zellymiriam commented on src/controllers/commentsController.js
> +
remove this line

2019-10-31 09:00 UTC, nakiwuge commented on src/helpers/commentsHelper.js
> +
remove this line

2019-10-31 09:00 UTC, nakiwuge commented on src/helpers/commentsHelper.js
> +  models.comments.update(data, { where: { id, }, });
add anew line

2019-10-31 09:05 UTC, nakiwuge requested changes
Good job @sabin18. Kindly work on the feedback below
- Return the updated comment object when a user successfully updates a comment
- Return the updated comment object when a user successfully deletes a comment
- Check the other comments I have left on your pr

2019-11-01 11:19 UTC, nakiwuge approved these changes

2019-11-01 11:19 UTC, merged