FT (Users add ratings): A user must add ratings against an accomodation
andela/caret-bn-backend pull request #39
Opened 2019-10-30 10:58 UTC by Cheza-Dzabala

#### What does this PR do?

Allows users to provide ratings on accommodations. 

#### Description of Task to be completed?

- Allow a user to provide feedback & ratings on accommodations.

#### How should this be manually tested?

1. Clone this Repository

2. Run ` npm install `

3. Run ` sequelize db:migrate `

4. Run ` sequelize db:seed:all `

5. Run ` npm run dev `

6. Log in with seeded user ` alain@caretbn.com `

7. Attempt to send  ` POST ` request to ` http://Localhost:<PORT>/api/v1/ratings/ `

```javascript 
{
	"accommodationId": INTEGER
	"rating": FLOAT
	"feedback": STRING || NULLABLE
}
```

8. When the booking is successful, you can view all ratings by sending a ` GET ` request to ` http://Localhost:<PORT>/api/v1/ratings/ <:slug>`

#### Any background context you want to provide?
N / A

#### What are the relevant pivotal tracker stories?

##### #168781711

#### Screenshots (if appropriate)

<img width="788" alt="Screen Shot 2019-10-30 at 12 57 19" src="https://user-images.githubusercontent.com/13886438/67852287-d308d580-fb14-11e9-861f-90ed12c1363e.png">

<img width="733" alt="Screen Shot 2019-10-30 at 12 52 36" src="https://user-images.githubusercontent.com/13886438/67852230-b7053400-fb14-11e9-942d-914123a11d65.png">

<img width="927" alt="Screen Shot 2019-10-30 at 12 54 26" src="https://user-images.githubusercontent.com/13886438/67852231-b7053400-fb14-11e9-8e8e-e0d1ce55df6b.png">

#### Questions:

N / A

2019-10-30 13:12 UTC, sabin18 requested changes

2019-10-30 13:12 UTC, sabin18 commented on src/middlewares/ratingsMiddleware.js
> +            403
the status code is 409.

2019-10-30 14:30 UTC, nignanthomas approved these changes
@Cheza-Dzabala Great job
The checks and validations 👍

2019-10-30 14:35 UTC, sabin18 approved these changes
good job @Cheza-Dzabala

2019-10-30 15:20 UTC, nakiwuge commented on src/controllers/ratingsController.js
> +        const accomodation = await accomodationServices.findOneAccommodation({
Make this a helper function

2019-10-30 15:23 UTC, zellymiriam commented on src/routes/api/ratings.js
> +
remove this line

2019-10-30 15:23 UTC, nakiwuge commented on src/services/bookingServices.js
> +
Remove this line

2019-10-30 15:32 UTC, nakiwuge requested changes
@Cheza-Dzabala good job. Kindly work on the feedback below.
- Users should be logged in tho view there ratings
- Users should provide feedback to when they give a rating of below 4
- Let us use whole nimbers for rating
- Users should view the average rating when viewing all accommodation and single accommodation.
- The feedback validation of at least 30 characters is too much for a user.
- Add a virtual boolean field `hasRated` when retrieving all accommodation and a single accommodation
Also, check the comments on the pr

2019-10-31 15:12 UTC, nakiwuge approved these changes

2019-10-31 15:12 UTC, merged