feature(add_comment): add and view comment
andela/caret-bn-backend pull request #40
Opened 2019-10-31 08:16 UTC by ngireric123

- create one endpoint for add/ view comment

        - create one controller for changeStatus

        - create a helper for comment

        - create a routes for API

        [starts #168781692]

#### What does this PR do?
- Add and view comments 
#### Description of Task to be completed?
- add the possibility for line manager and owner of the request to add a comment on the request
- add the possibility for line manager and owner of the request to view a comment on the request
#### How should this be manually tested?
- Browse to the repo directory
- navigate to Ft-comment-168781692 branch
- Run `npm install`
- run `sequelize db:migrate`
- run `sequelize db:seed:all`
- run `npm run dev`
#### Any background context you want to provide?
**To add a comment**
- In Postman Provide a login bearer token
- Fill the body with comment field
- send a `POST` request to `http://localhost:<:port>/api/v1/comments/:id`

**To view a comment**
- In Postman Provide a login bearer token
- send a `GET` request to `http://localhost:<:port>/api/v1/comments/:id`
#### What are the relevant pivotal tracker stories?
[#168781692](https://www.pivotaltracker.com/story/show/168781692)
#### Screenshots (if appropriate)
![image](https://user-images.githubusercontent.com/38130305/67929988-64d11b00-fbc7-11e9-83dd-42cba00a8232.png)

#### Questions:
N/A

2019-10-31 17:58 UTC, alainmateso approved these changes
Great job Eric. Kindly change the message that you return when posting a comment and make it comment-related. I think the user is posting a comment not updating a request. Other than that, well done.

2019-10-31 18:11 UTC, alainmateso commented on src/routes/api/comments.js
> +// const { checkExistingRequest } = commentMiddleware;
Remove this commented line

2019-10-31 18:50 UTC, sabin18 approved these changes

2019-11-01 07:39 UTC, zellymiriam commented on src/controllers/commentsController.js
> +    const requestId = parseInt(req.params.id, 10);
Add a new line here

2019-11-01 07:40 UTC, zellymiriam commented on src/controllers/commentsController.js
> +
Remove this line

2019-11-01 07:41 UTC, zellymiriam commented on src/controllers/commentsController.js
> +        where: { requestId }
This gets all comments on a request even the soft deleted ones. Add a condition to get comments only when the `deleted= false`

2019-11-01 07:43 UTC, zellymiriam commented on src/middlewares/commentMiddleware.js
> +const commentMiddle = {
Get this a better name please

2019-11-01 07:44 UTC, zellymiriam commented on src/routes/api/comments.js
> +
remove this line

2019-11-01 07:44 UTC, zellymiriam commented on src/routes/api/comments.js
> +
remove this line

2019-11-01 07:45 UTC, zellymiriam commented on src/routes/api/comments.js
> +
remove this line

2019-11-01 07:45 UTC, zellymiriam commented on src/tests/comment.spec.js
> +
remove this line

2019-11-01 07:46 UTC, zellymiriam commented on src/controllers/commentsController.js
> +
remove this line

2019-11-01 07:50 UTC, nakiwuge requested changes
@ngireric123 good job. Kindly work on the feedback below.
- Return the user object you can return `id, username and email` when retrieving comments
- Add your endpoints to swagger
- Check out the comments I have left on the pr

2019-11-01 09:32 UTC, nakiwuge approved these changes

2019-11-01 09:32 UTC, merged