FT(Users Mark All Notifications): All users Mark Notifications
andela/caret-bn-backend pull request #45
Opened 2019-11-04 15:55 UTC by Cheza-Dzabala

#### What does this PR do?
Allows users to mark all their notification as read

#### Description of Task to be completed?
Enable an authenticated user to mark all their tasks as read.

#### How should this be manually tested?

1. Clone this repository
2. Run ` sequelize db:migrate `
3. Run ` sequelize db:seed:All `
4. Run ` npm run dev `
5. Log into the application at `api/v1/users/login`
6. Using an  authenticated user send a patch request to `api/v1/notifications/mark/read`

#### Any background context you want to provide?
N /A 
#### What are the relevant pivotal tracker stories?
##### #168781713

#### Screenshots (if appropriate)

<img width="1172" alt="Screen Shot 2019-11-04 at 17 06 41" src="https://user-images.githubusercontent.com/13886438/68131576-f4f3c500-ff25-11e9-9354-2da38b5ca5d1.png">
<img width="1258" alt="Screen Shot 2019-11-04 at 17 06 31" src="https://user-images.githubusercontent.com/13886438/68131575-f4f3c500-ff25-11e9-9ad1-755d71a9e174.png">
<img width="1044" alt="Screen Shot 2019-11-04 at 17 09 42" src="https://user-images.githubusercontent.com/13886438/68131578-f58c5b80-ff25-11e9-82c5-85bc06f0fc0f.png">
<img width="875" alt="Screen Shot 2019-11-04 at 17 09 46" src="https://user-images.githubusercontent.com/13886438/68131581-f624f200-ff25-11e9-996a-dd66abad0ef9.png">

#### Questions:

N / A

2019-11-04 16:22 UTC, alainmateso approved these changes
Gooj Job Cheza

2019-11-04 16:51 UTC, nignanthomas approved these changes
Great job @Cheza-Dzabala

2019-11-05 08:25 UTC, nakiwuge commented on src/controllers/notificationController.js
> +    const notifications = await allNotif(query);
Add a new line here

2019-11-05 08:27 UTC, nakiwuge commented on src/controllers/notificationController.js
> +    const query = { where: { userNotified: req.user.payload.id } };
Kindly include the userObj

2019-11-05 08:27 UTC, nakiwuge commented on src/controllers/notificationController.js
> +      const message = `This notification status has been marked as ${status}read`;
add anew line

2019-11-05 08:29 UTC, nakiwuge commented on src/controllers/notificationController.js
> +    const notifications = await notifServices.allNotif(query);
add anew line

2019-11-05 08:32 UTC, nakiwuge requested changes
@Cheza-Dzabala good job. Kindly allow users to switch between `mark as read` and `mark as unread`.
Also, check out the comments I have left on the pr

2019-11-05 11:27 UTC, nakiwuge commented on src/controllers/notificationController.js
> +
Remove this line

2019-11-05 11:27 UTC, nakiwuge commented on src/controllers/notificationController.js
> +
Remove this line

2019-11-05 11:27 UTC, nakiwuge commented on src/controllers/notificationController.js
> +
Remove this line

2019-11-05 11:27 UTC, nakiwuge commented on src/controllers/notificationController.js
> +
Remove this line

2019-11-06 10:09 UTC, nakiwuge approved these changes

2019-11-06 10:10 UTC, merged