FT (User can view destinations): Users can view travelled Destinations
andela/caret-bn-backend pull request #46
Opened 2019-11-05 06:19 UTC by Cheza-Dzabala

#### What does this PR do?

This PR enables authenticated users to view the top 5 most travelled locations in the barefoot nomad system. 

#### Description of Task to be completed?

- Allow users and managers to view the top 5 travelled locations in the barefoot nomad system.

#### How should this be manually tested?

1. Clone this repository
2. Run ` sequelize db:migrate `
3. Run ` sequelize db:seed:All `
4. Run ` npm run dev `
5. Log into the application at `api/v1/users/login`
6. Using an  authenticated user send a GET request to `/api/v1/destinations/top-locations`
7. It should display the top 5 locations visited in barefoot nomad. 
8. Incase 4 locations are displayed. Manually change the status of one or more requests to status id `3` and run the endpoint again

#### Any background context you want to provide?

N / A

#### What are the relevant pivotal tracker stories?

###### #168781713

#### Screenshots (if appropriate)

<img width="1228" alt="Screen Shot 2019-11-05 at 08 18 23" src="https://user-images.githubusercontent.com/13886438/68183365-e4366400-ffa4-11e9-9738-c1834be9116f.png">
<img width="1264" alt="Screen Shot 2019-11-05 at 08 18 30" src="https://user-images.githubusercontent.com/13886438/68183366-e4366400-ffa4-11e9-9972-20c7a22e7ff2.png">
<img width="818" alt="Screen Shot 2019-11-05 at 08 18 35" src="https://user-images.githubusercontent.com/13886438/68183367-e4366400-ffa4-11e9-8925-d420bd37b3e3.png">

#### Questions:
N / A

2019-11-05 09:39 UTC, sabin18 requested changes
good job @cheza , here are some changes that you can make on this PR:
-  change message to `Top 5 visited locations`
- There is a middleware which check supplier role use it to check supplier instead of creating new one.

2019-11-05 12:16 UTC, nignanthomas commented on src/tests/adminTest.spec.js
> +  xit('Should asign role to user twice', done => {
Why do you `xit` this test?

2019-11-05 12:17 UTC, nignanthomas requested changes
Great job @Cheza-Dzabala 
I left a comment

2019-11-05 12:50 UTC, nakiwuge commented on src/controllers/destinationController.js
> +
remove this line

2019-11-05 12:50 UTC, nakiwuge commented on src/controllers/destinationController.js
> +
remove this line

2019-11-05 12:54 UTC, nakiwuge commented on src/routes/api/destinations.js
> +router.get('/top-locations', (req, res) => destinationController.viewTopDestinations(req, res));
Change `/top-location` to most visited

2019-11-05 12:55 UTC, nakiwuge requested changes
@Cheza-Dzabala great job. Kindly check out the comments I have left on this pr

2019-11-06 12:34 UTC, sabin18 approved these changes

2019-11-06 15:06 UTC, nignanthomas approved these changes

2019-11-07 08:10 UTC, nakiwuge approved these changes

2019-11-07 08:11 UTC, merged