feature(like/unlike): user should be to like/unlike accommodation fac…
andela/caret-bn-backend pull request #49
Opened 2019-11-06 12:36 UTC by ngireric123

#### What does this PR do?

 like/unlike an accommodation facility

#### Description of Task to be completed?
- Allow users to like/unlike accommodation facilities.

#### How should this be manually tested?
##### like/unlike accommodation
1. Clone this repository
2. Run ` sequelize db:migrate `
3. Run ` sequelize db:seed:All `
4. Run ` npm run dev `
5. Log into the application at `api/v1/users/login`
6. Using an  authenticated user send a POST request to `/api/v1/accommodations/${id}/like`
7. It should like/unlike accommodation facilities. 

##### Get number of likes

1. Using an  authenticated user send a POST request to `/api/v1/accommodations/${slug}`
2. It should display details of accommodation and its likes

#### Any background context you want to provide?

N / A

#### What are the relevant pivotal tracker stories?
[#168781709](https://www.pivotaltracker.com/story/show/168781709)
#### Screenshots (if appropriate)

![image](https://user-images.githubusercontent.com/38130305/68298745-d1a25480-00a2-11ea-9008-b7dd17e9927c.png)

![image](https://user-images.githubusercontent.com/38130305/68298696-a7e92d80-00a2-11ea-9857-1a121e0bce0c.png)

#### Questions:

N/A

2019-11-07 08:27 UTC, Cheza-Dzabala requested changes
Hey Eric. Well done. However, please use lowercase for the DB table names not uppercase. Secondly, the error message returned should be refactored to something like: "The specified accommodation does not exist in our system." Otherwise, great work.

2019-11-07 09:28 UTC, sabin18 approved these changes
Good job @ngireric123 .

2019-11-07 10:07 UTC, nakiwuge commented on src/routes/api/accommodations.js
> +router.post('/:id/like', validateToken, checkId, likeValidation, likeAccommodation);
Make this route dynamic to cater for like and dislike you can add something like this `/:id/:action`

2019-11-07 10:10 UTC, nakiwuge commented on src/services/accommodationServices.js
> +    if (!accommodation) return null;
Move this condition inside the then on line 7 and do away with this function

2019-11-07 10:14 UTC, nakiwuge commented on src/services/likesServices/likesServices.js
> +      where: { accommodationId: accommodation, user_id: userId }
This condition will only allow users who have liked and accommodation to view the total number of likes in an accommodation. We should allow users to view the total number of likes/dislikes on an accommodation whether they have liked that accommodation or not

2019-11-07 10:19 UTC, nakiwuge commented on src/services/likesServices/likesServices.js
> +    await models.Likes.update(status, {
You should only update when the passed param is `dislike`

2019-11-07 10:22 UTC, nakiwuge commented on src/services/likesServices/likesServices.js
> +    const idAccommodation = await models.accommodations.findOne({
rename `idAccommodation` to `accomodation`

2019-11-07 10:22 UTC, nakiwuge commented on src/services/likesServices/likesServices.js
> +      const accommodation = idAccommodation.id;
rename `accommodation` to  `accommodationId`

2019-11-07 10:23 UTC, nakiwuge commented on src/tests/accommodationTest.spec.js
> +      console.log(err);
remove the console

2019-11-07 10:29 UTC, nakiwuge requested changes
@ngireric123 great job on the implementation kindly works on the feedback below.
- Add total number of dislikes when fetching accomodations and a single accommodation.
- Add `hasLiked` and `hasDisliked` boolean keys when fetching accommodations  and a single accommodation 
Also check on the feedback I have left on this pr

2019-11-13 12:38 UTC, Cheza-Dzabala requested changes
Please see comments on PR.

2019-11-13 12:38 UTC, Cheza-Dzabala commented on src/database/migrations/20191105100202-create-likes.js
> +    return queryInterface.createTable('Likes', {
Make tables lowercase

2019-11-13 12:38 UTC, Cheza-Dzabala commented on src/database/models/accommodations.js
> +      foreignKey: "owner",
This should be ` userId ` not ` owner `

2019-11-13 12:38 UTC, Cheza-Dzabala commented on src/database/models/accommodations.js
> +      owner: DataTypes.INTEGER,
This should be userId not owner

2019-11-13 12:38 UTC, Cheza-Dzabala commented on src/database/models/accommodations.js
> +      as: "ownerUser",
This should just be `owner`. Not `ownerUser`

2019-11-13 12:38 UTC, Cheza-Dzabala commented on src/database/models/accommodations.js
> +      as: "accommodationLocation",
Relation name should be ` location `. Not  ` accommodationLocation `

2019-11-13 12:38 UTC, Cheza-Dzabala commented on src/database/models/likes.js
> +  const Likes = sequelize.define('Likes', {
Lowercase table names only

2019-11-13 15:18 UTC, nignanthomas approved these changes
@ngireric123 
Great job man
Rien à signaler

2019-11-14 08:36 UTC, nakiwuge approved these changes

2019-11-14 08:36 UTC, merged