#168781714 add chat functionality
andela/caret-bn-backend pull request #50
Opened 2019-11-06 16:09 UTC by alainmateso

- Adds chat functionality for logged in users
[Finishes#168781714]

#### What does this PR do?
Add chat functionality

#### Description of Task to be completed?
- Adds chat functionality for logged in users
- Adds the chat interface

#### How should this be manually tested?
- Clone the repository from [here](https://github.com/andela/caret-bn-backend.git)
- Browse to the repo directory
- navigate to ft-users-chat-168781714 branch
- Run `npm install`
- run `sequelize db:migrate`
- run `sequelize db:seed:all`
- run `npm run dev`

To chat

- In Postman, login and copy the token
- Paste the token into the local storage of the browser
- In the browser, navigate to localhost:3000
You should see an interface that provides the text input and send button
Type your messages, hit send, and your messages as well as those from everyone connected should appear in the console

To view the chat history

- In Postman Provide a login bearer token
- send a `GET` request to `http://localhost:<:port>/api/v1/chat`

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
#168781714
#### Screenshots (if appropriate)
<img width="1264" alt="Screen Shot 2019-11-06 at 18 06 15" src="https://user-images.githubusercontent.com/50104386/68315381-5bace600-00c0-11ea-8440-a9ccd61f2a00.png">
<img width="1440" alt="Screen Shot 2019-11-06 at 18 06 33" src="https://user-images.githubusercontent.com/50104386/68315383-5c457c80-00c0-11ea-87cb-3460459be0ad.png">
<img width="1173" alt="Screen Shot 2019-11-06 at 18 07 35" src="https://user-images.githubusercontent.com/50104386/68315384-5c457c80-00c0-11ea-8be8-64923aac8c77.png">

#### Questions:
N/A

2019-11-07 10:39 UTC, Cheza-Dzabala approved these changes
The only concern is the coverage... But that aside, I approve.

2019-11-07 11:03 UTC, sabin18 requested changes
@alainmateso good job however It would be batter if you use username in place of email .

2019-11-07 11:20 UTC, alainmateso commented
> @alainmateso good job however It would be batter if you use username in place of email .

Well noted and implemented. Thanks for the feedback

2019-11-07 12:09 UTC, sabin18 approved these changes
@alainmateso good job.

2019-11-07 12:12 UTC, nakiwuge commented on src/controllers/chatController.js
> +const verifyToken = token => {
rename this to `verifyToken` to `getLoggedInUser`

2019-11-07 12:15 UTC, nakiwuge commented on src/controllers/chatController.js
> +    io.emit('chatMessage', { sender: userInfo.username, message });
Putt this in a try and catch

2019-11-07 12:17 UTC, nakiwuge commented on src/controllers/chatController.js
> +  io.use((socket, next) => {
Putt this in a try and catch

2019-11-07 12:17 UTC, nakiwuge commented on src/controllers/chatController.js
> +  socket.on('chatMessage', async (chatObject) => {
Putt this in a try and catch

2019-11-07 12:22 UTC, nakiwuge commented on src/index.html
> +        const socket = io("http://localhost:3000", {
Make the url dynamic

2019-11-07 12:27 UTC, nakiwuge commented on src/routes/api/index.js
> +router.use('/chat', chatRoutes);
rename this `/chat` to `/chats`

2019-11-07 12:28 UTC, nakiwuge requested changes
@alainmateso great job on the implementation. Kindly check out the comments I have left on this pr

2019-11-08 05:12 UTC, nakiwuge approved these changes

2019-11-08 05:12 UTC, merged