#169469640 - Approving and Rejecting Bookings
andela/caret-bn-backend pull request #51
Opened 2019-11-07 07:45 UTC by nignanthomas

#### What does this PR do?
Approving and Rejecting Bookings.

#### Description of Task to be completed?
- Add statusId to booking field
- Create route for filtering bookings by status
- Create a patch route to approve/reject bookings
- Create tests for this feature

#### How should this be manually tested?
- Clone the repository from [here](https://github.com/andela/caret-bn-backend.git)
- Browse to the repo directory
- navigate toft-approve-reject-booking-169469640 branch
- Run `npm install`
- run `sequelize db:migrate`
- run `sequelize db:seed:all`
- run `npm run dev`

**To add a filter bookings**
- In Postman Provide a login bearer token as a supplier
- send a `GET` request to `http://localhost:<:port>/api/v1/accommodations/bookings/search?status={status}`
status can be `pending`, `approved`, `rejected`.

**To approve/reject a booking**
- In Postman Provide a login bearer token as a supplier
- send a `PATCH` request to `http://localhost:<:port>/api/v1/accommodations/bookings/approve/{id}
- send a `PATCH` request to `http://localhost:<:port>/api/v1/accommodations/bookings/reject/{id}

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
[#169469640](https://www.pivotaltracker.com/story/show/169469640)

#### Screenshots (if appropriate)
<img width="1136" alt="Screen Shot 2019-11-07 at 09 41 39" src="https://user-images.githubusercontent.com/42959540/68369524-39a87780-0143-11ea-887d-b3465d4c28c7.png">
<img width="1117" alt="Screen Shot 2019-11-07 at 09 43 09" src="https://user-images.githubusercontent.com/42959540/68369527-3ca36800-0143-11ea-95b0-64fe80c6cb13.png">

#### Questions:
N/A

2019-11-07 16:59 UTC, ngireric123 approved these changes
good job Thomas but you decrease coveralls kindly increase them

2019-11-07 18:58 UTC, alainmateso requested changes
Good job Thomas! however, please ensure that a supplier can only see bookings made to accommodations they own and please return data objects when possible. FOr example when viewing bookings, you can return the user's details as well as the booked accommodation details as well as the status name instead of statusId.

2019-11-08 07:48 UTC, alainmateso approved these changes

2019-11-08 08:36 UTC, nakiwuge commented on src/controllers/accommodationController.js
> +    let myBookings = [];
Add a new line

2019-11-08 08:41 UTC, nakiwuge commented on src/database/models/bookingnotifications.js
> +  const bookingnotifications = sequelize.define('bookingnotifications', {
change table name to  `booking_notifications`

2019-11-08 08:45 UTC, nakiwuge commented on src/tests/bookingsTests.spec.js
> +
remove this line

2019-11-08 08:46 UTC, nakiwuge commented on src/middlewares/bookingFound.js
> +  const booking = await bookingHelper.findOneBooking({ id });
Add new line

2019-11-08 08:46 UTC, nakiwuge commented on src/middlewares/bookingNotPending.js
> +
remove this line

2019-11-08 08:52 UTC, nakiwuge requested changes
Good job @nignanthomas, kindly check out the comments I have left on your pr.

2019-11-10 16:40 UTC, nakiwuge approved these changes

2019-11-10 16:40 UTC, merged