#168781706 -Managers should get notifications for edited requests
andela/caret-bn-backend pull request #53
Opened 2019-11-11 08:38 UTC by sabin18

#### What does this PR do?
PR to allow Managers to get notifications for edited requests
#### Description of Task to be completed?
- add notification function
#### How should this be manually tested?
- clone the repository : git clone https://github.com/andela/caret-bn-backend.git
- checkout to branch get-notifications-168781706
- run sequelize db:migrate
- run sequelize db:seed:all
- use this route to edit request `PATCH :/api/v1/requests/requests/:id.
- use this route to get notifications `GET: /api/v1//notifications/.
#### Any background context you want to provide?
`N/A`
#### What are the relevant pivotal tracker stories?
[#168781706](https://www.pivotaltracker.com/story/show/168781706)
#### Screenshots (if appropriate)
<img width="1028" alt="Screen Shot 2019-11-11 at 10 33 58" src="https://user-images.githubusercontent.com/47029978/68572721-d41ff800-046e-11ea-9d1a-7a05e653792f.png">
#### Questions:
`N/A`

2019-11-11 10:32 UTC, alainmateso approved these changes
Good Job Sabin

2019-11-11 13:58 UTC, nignanthomas commented on src/controllers/requestController.js
> +        `request ${id} has been edited . Click here to view: ${APP_URL_BACKEND}/api/v1/requests/${id}.`
Kindly edit the message into `A request has been edited...` or `The request of id: ${id} has been edited...`

2019-11-11 13:59 UTC, nignanthomas commented on src/routes/api/requests.js
> -
Add a line here 😏

2019-11-11 14:00 UTC, nignanthomas requested changes
Great job bro @sabin18 
I left some comments on your PR.

2019-11-12 07:32 UTC, nignanthomas approved these changes

2019-11-12 12:07 UTC, merged