#169649045 -User should be able to Chat with a supplier and line manager
andela/caret-bn-backend pull request #59
Opened 2019-11-13 16:05 UTC by sabin18

#### What does this PR do?
PR to allow a user to Chat with a supplier and line manager
#### Description of Task to be completed?
- add a private chat function
#### How should this be manually tested?
- clone the repository : git clone https://github.com/andela/caret-bn-backend.git
- checkout to branch ft-get-stats-trips-168781712
- run sequelize db:migrate
- run sequelize db:seed:all
- use this route to chat `http://localhost:3000/`
- use this route to get privatechat `{{host}}/api/v1/chats/private`
- add token  in your local storage of browser
- add userId to whom you want to chat  in your local storage of browser
-add messageType   in your local storage of browser and set it as private

#### Any background context you want to provide?
`N/A`
#### What are the relevant pivotal tracker stories?
[#169649045](https://www.pivotaltracker.com/story/show/169649045)
#### Screenshots (if appropriate)
<img width="1427" alt="Screen Shot 2019-11-13 at 17 16 21" src="https://user-images.githubusercontent.com/47029978/68780833-80b0d400-063f-11ea-8146-c44b9fdc4b47.png">
<img width="1021" alt="Screen Shot 2019-11-13 at 18 01 52" src="https://user-images.githubusercontent.com/47029978/68780975-b950ad80-063f-11ea-9ecc-c2cf58bae366.png">
#### Questions:
`N/A`

2019-11-14 10:42 UTC, nignanthomas commented on src/database/seeders/20191114085254-chat.js
> +    queryInterface.bulkDelete('bookmarks', null, {})
It should be `'chats'` not `'bookmarks'`.

2019-11-14 10:45 UTC, nignanthomas commented on src/index.js
> +
Remove this line.

2019-11-14 13:34 UTC, nignanthomas requested changes
That is some really nice stuff here @sabin18 
I left some comments. Kindly work on that.
And try your best to raise the coverage

2019-11-14 13:34 UTC, nignanthomas commented on src/database/migrations/20191106111952-create-chats.js
> +      },
Please create a new migration file to add this column. Thanks.

2019-11-15 08:12 UTC, nignanthomas approved these changes

2019-11-15 09:41 UTC, ngireric123 approved these changes
@sabin18 you did a great job but try to increase the coverage

2019-11-18 08:14 UTC, alainmateso approved these changes

2019-11-18 20:05 UTC, merged