Ch set sequelize and postgres sql
andela/caret-bn-backend pull request #6
Opened 2019-10-01 06:03 UTC by ngireric123

#### What does this PR do?
* Setup Sequelize and PostgresSQL
### Description of Task to be completed?
* install sequelize-cli
* install --save path
* install --save sequelize pg pg-hstore
* sequelize initialization
* install --save dotenv
* creating config.js
* setting dotenv file
* creating Database, modal, and Migration
* Create Services, Controllers, Routes, and Utilities
* edit controller, services and model file
#### How should this be manually tested?
* clone repository
* Run npm install
* create .env file
* run sequelize db:migrate
### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
#168781663
#### Screenshots (if appropriate)
N/A
#### Questions:
N/A

2019-10-02 10:46 UTC, Cheza-Dzabala reviewed
@ngireric123 Please correct ` hound ` warnings

2019-10-02 14:57 UTC, Cheza-Dzabala reviewed
<img width="690" alt="Screen Shot 2019-10-02 at 16 56 27" src="https://user-images.githubusercontent.com/13886438/66055310-a1ace200-e535-11e9-99a9-c4a4cfe32e2b.png">

Please resolve this first

2019-10-02 19:22 UTC, alainmateso requested changes
Please make use of .env.example and provide all necessary environment variables for others to be able to run this.

2019-10-02 19:50 UTC, sabin18 requested changes

2019-10-02 19:50 UTC, sabin18 commented on src/database/models/index.js
> +const fs = require('fs');
you did a great job but it is better to use ES6 by using import here .

2019-10-02 20:33 UTC, sabin18 approved these changes
it looks good.

2019-10-03 07:37 UTC, Cheza-Dzabala submitted a review, later dismissed
All good

2019-10-03 08:22 UTC, alainmateso submitted a review, later dismissed

2019-10-03 12:59 UTC, Cheza-Dzabala approved these changes

2019-10-03 12:59 UTC, alainmateso approved these changes

2019-10-03 13:22 UTC, merged