#168781682-Logout user
andela/caret-bn-backend pull request #61
Opened 2019-11-14 10:36 UTC by ngireric123

- Added column on user table

    - Added logout function in user controller

    - create router for logout

    - create tests for logout

    [Finishes #168781682]

#### What does this PR do?

User Logout

#### Description of Task to be completed?
   - Add column on user table

   - Add logout function in user controller

   - create router for logout

   - create tests for logout

#### How should this be manually tested?

- Clone the repository from [here](https://github.com/andela/caret-bn-backend.git)
- Browse to the repo directory
- navigate to ch-notifications-timestamp-169749860 branch
- Run `npm install`
- run `sequelize db:migrate`
- run `sequelize db:seed:all`
- run `npm run dev`
- Using an authenticated user send a PATCH request to /api/v1/users/logout

#### Any background context you want to provide?

N/A

#### What are the relevant pivotal tracker stories?
(https://www.pivotaltracker.com/story/show/168781682)[168781682]
#### Screenshots (if appropriate)

![image](https://user-images.githubusercontent.com/38130305/68849763-590f4980-06db-11ea-8ea2-3b3235393cc6.png)

#### Questions:
N/A

2019-11-14 16:31 UTC, alainmateso approved these changes

2019-11-14 16:46 UTC, nignanthomas commented on src/utils/stringsUtil.js
> +      LOGOUT: 'user Logout successful'
Kindly change the message into something like `You have been logged out successfully!`

2019-11-14 16:50 UTC, nignanthomas requested changes
Nice job @ngireric123 
Kindly implement the requested changes.
Thanks

2019-11-15 11:07 UTC, nignanthomas approved these changes

2019-11-19 14:34 UTC, merged